Fix typo causing local variable 'ex' referenced before assignment
```
Traceback (most recent call last):
  File "/usr/bin/sr", line 11, in <module>
    load_entry_point('metpx-sarracenia===2.22.10p2', 'console_scripts', 'sr')()
  File "/usr/lib/python3/dist-packages/sarra/sr.py", line 1108, in main
    gs.start()
  File "/usr/lib/python3/dist-packages/sarra/sr.py", line 806, in start
    self._launch_instance(component_path, c, cfg, i)
  File "/usr/lib/python3/dist-packages/sarra/sr.py", line 106, in _launch_instance
    print( 'makedirs %s failed: %s' % ( os.path.dirname(lfn), ex ) )
UnboundLocalError: local variable 'ex' referenced before assignment
```